### ISSUE TITLE
Failed to activate the test-runner package

### ISSUE THREAD

**Issue by bcroq** [go2sh/test-runner#1]
Steps to reproduce:

1. install test-runner (or enable it)

**Atom**: 1.16.0 x64
**Electron**: 1.4.16
**OS**: "Arch Linux"
**Thrown From**: [test-runner](https://github.com/go2sh/test-runner) package 1.0.1

### Stack Trace

Failed to activate the test-runner package

```
At path is not defined

ReferenceError: path is not defined
    at loadTestConfigs (/packages/test-runner/dist/package.js:719:27)
    at Array.wrappedActionHandler (/packages/test-runner/node_modules/vuex/dist/vuex.js:604:15)
    at Store.dispatch (/packages/test-runner/node_modules/vuex/dist/vuex.js:347:15)
    at /packages/test-runner/node_modules/vuex/dist/vuex.js:272:21)
    at Object.activate (/packages/test-runner/dist/package.js:67:33)
    at Package.module.exports.Package.activateNow (/usr/lib/atom/src/package.js:218:19)
    at /usr/lib/atom/src/package.js:190:32
    at Package.module.exports.Package.measure (/usr/lib/atom/src/package.js:96:15)
    at /usr/lib/atom/src/package.js:183:26
    at Package.module.exports.Package.activate (/usr/lib/atom/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/lib/atom/src/package-manager.js:542:34)
    at /usr/lib/atom/src/package-manager.js:344:19
    at /usr/lib/atom/src/config.js:635:20
    at Function.module.exports.Emitter.simpleDispatch (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:141:28)
    at Config.module.exports.Config.emitChangeEvent (/usr/lib/atom/src/config.js:826:29)
    at Config.module.exports.Config.setRawValue (/usr/lib/atom/src/config.js:612:19)
    at Config.module.exports.Config.set (/usr/lib/atom/src/config.js:227:14)
    at Config.module.exports.Config.removeAtKeyPath (/usr/lib/atom/src/config.js:377:12)
    at Package.module.exports.Package.enable (/usr/lib/atom/src/package.js:81:26)
    at PackageManager.module.exports.PackageManager.enablePackage (/usr/lib/atom/src/package-manager.js:165:14)
    at HTMLButtonElement.enablementButtonClickHandler (/usr/lib/atom/node_modules/settings-view/lib/package-card.js:353:25)
```

### Commands

```
     -4:37.5.0 core:move-left (div.panels-item)
     -4:37.1.0 core:move-down (div.panels-item)
  3x -4:36.5.0 core:move-up (div.panels-item)
     -4:24.1.0 core:confirm (input.hidden-input)
     -3:59 core:page-down (div.package-detail.panels-item)
     -2:11.6.0 command-palette:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -2:10.4.0 core:confirm (input.hidden-input)
     -2:10.3.0 application:show-preferences (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -2:09.2.0 command-palette:toggle (div.panels-item)
     -2:06.4.0 core:backspace (input.hidden-input)
     -2:00.9.0 core:move-down (input.hidden-input)
     -2:00.6.0 core:move-up (input.hidden-input)
     -2:00.1.0 core:confirm (input.hidden-input)
     -2:00.1.0 settings-view:install-packages-and-themes (div.panels-item)
     -1:54 core:backspace (input.hidden-input)
     -1:52.4.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.23 
busy-signal 1.4.1 
intentions 1.1.2 
jslint 1.5.1 
linter 2.1.4 
linter-flake8 2.2.1 
linter-ui-default 1.2.3 
test-runner 1.0.1 
```

**Comment by go2sh** [comment]
Actually, I never tested it on linux. Maybe the arch electron package doesn't autoload the path module. I'll fix it tonight (CEST).

**Comment by beorn** [comment]
I'm having this issue on MacOS

```
ReferenceError: path is not defined
    at loadTestConfigs (/Users/bjorn/.atom/packages/test-runner/dist/package.js:719:32)
    at Array.wrappedActionHandler (/Users/bjorn/.atom/packages/test-runner/node_modules/vuex/dist/vuex.js:604:15)
    at Store.dispatch (/Users/bjorn/.atom/packages/test-runner/node_modules/vuex/dist/vuex.js:347:15)
    at Store.boundDispatch [as dispatch] (/Users/bjorn/.atom/packages/test-runner/node_modules/vuex/dist/vuex.js:272:21)
    at Object.activate (/Users/bjorn/.atom/packages/test-runner/dist/package.js:67:33)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:253:25)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:645:40)
    at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:603:52)
    at /Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:843:36
```

**Comment by lokeshmeher** [comment]
On Ubuntu 18.04.1 LTS (4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux):
```
ReferenceError: path is not defined
    at Store.loadTestConfigs (/home/lokesh/.atom/packages/test-runner/dist/package.js:719:27)
    at Array.wrappedActionHandler (/home/lokesh/.atom/packages/test-runner/node_modules/vuex/dist/vuex.common.js:706:23)
    at Store.dispatch (/home/lokesh/.atom/packages/test-runner/node_modules/vuex/dist/vuex.common.js:428:15)
    at Store.boundDispatch [as dispatch] (/home/lokesh/.atom/packages/test-runner/node_modules/vuex/dist/vuex.common.js:334:21)
    at Object.activate (/home/lokesh/.atom/packages/test-runner/dist/package.js:67:33)
    at Package.activateNow (/snap/atom/192/usr/share/atom/resources/app/src/package.js:230:33)
    at measure (/snap/atom/192/usr/share/atom/resources/app/src/package.js:206:33)
    at Package.measure (/snap/atom/192/usr/share/atom/resources/app/src/package.js:88:25)
    at activationPromise.Promise (/snap/atom/192/usr/share/atom/resources/app/src/package.js:200:20)
    at new Promise (<anonymous>)
    at Package.activate (/snap/atom/192/usr/share/atom/resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (/snap/atom/192/usr/share/atom/resources/app/src/package-manager.js:695:42)
    at config.transactAsync (/snap/atom/192/usr/share/atom/resources/app/src/package-manager.js:670:36)
    at Config.transactAsync (/snap/atom/192/usr/share/atom/resources/app/src/config.js:866:28)
    at PackageManager.activatePackages (/snap/atom/192/usr/share/atom/resources/app/src/package-manager.js:668:23)
    at PackageManager.activate (/snap/atom/192/usr/share/atom/resources/app/src/package-manager.js:647:50)
    at loadStatePromise.loadState.then (/snap/atom/192/usr/share/atom/resources/app/src/atom-environment.js:875:27)
    at <anonymous>
```

**Comment by romansen47** [comment]
On Windows 10:
```
ReferenceError: path is not defined
    at Store.loadTestConfigs (/packages/test-runner/dist/package.js:719:27)
    at Array.wrappedActionHandler (/packages/test-runner/node_modules/vuex/dist/vuex.common.js:706:23)
    at Store.dispatch (/packages/test-runner/node_modules/vuex/dist/vuex.common.js:428:15)
    at /packages/test-runner/node_modules/vuex/dist/vuex.common.js:334:21)
    at Object.activate (/packages/test-runner/dist/package.js:67:33)
    at Package.activateNow (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:3405731)
    at measure (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:3405143)
    at Package.measure (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:3402753)
    at activationPromise.activationPromise.Promise (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:3405003)
    at new Promise (<anonymous>)
    at Package.activate (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:3404946)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:382285)
    at ~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:937303
    at r (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:931909)
    at n (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:14:1128986)
    at ChildProcess.o.process.on.e (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:14:1129192)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
```

### Commands

```
     -4:27.1.0 tree-view:reveal-active-file (span.hard-tab.leading-whitespace.indent-guide)
     -3:18.2.0 command-palette:toggle (summary.welcome-summary.icon.icon-keyboard)
     -3:13.1.0 core:confirm (input.hidden-input)
     -3:13.1.0 window:toggle-menu-bar (summary.welcome-summary.icon.icon-keyboard)
  2x -3:00.7.0 command-palette:toggle (summary.welcome-summary.icon.icon-keyboard)
 16x -1:38.6.0 core:backspace (input.hidden-input)
     -1:33.1.0 core:confirm (input.hidden-input)
     -0:58.6.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-console 0.4.6 
atom-java-decompiler 0.1.2 
atom-js-console 1.2.2 
atom-material-ui 2.1.3 
atom-maven 1.3.2 
atom-test-runner 0.11.1 
autocomplete-java 1.2.7 
busy 0.7.0 
busy-signal 2.0.1 
github-issue-blog 0.1.0 
github-search 0.1.0 
github-utils 1.6.0 
ide-java 0.9.0 
ide-python 1.4.2 
intentions 1.1.5 
Java-Bytecode-Disassembler 0.12.6 
java-class-complete 0.0.6 
java-classpath-registry 0.4.0 
java-generator 2.2.3 
linter 2.3.1 
linter-javac 1.10.0 
linter-ui-default 1.8.0 
test-runner 1.0.1 
```
